//'use server'
import type { Metadata } from "next";
//import { cache } from 'react';
//import cacheTeam from "@/app/helpers/cacheTeam";

import TeamProvider from "@/app/contextProviders/teamProvider";

import Overview from "@/app/teams/[teamID]/@tabs/overview/page";
import ScheduleHome from "@/app/teams/[teamID]/@tabs/schedule/page";
import RosterHome from "@/app/teams/[teamID]/@tabs/roster/page";
//import Statistics from "@/app/teams/[teamID]/@tabs/statistics/page";
import StatisticsHome from "@/app/teams/[teamID]/@tabs/statistics/page";
import Tabs from "@/app/components/Tabs";
import allTeamsColors from '@/app/data/allTeamsColors.json';


export const metadata: Metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
};

//export const getTeam = cache(cacheTeam);

export default async function RootLayout({ children, ...props }) {
  //const teamID = props.params.teamID;
  const { teamID } = await props.params;
  //console.log(teamID)
  const teamName = allTeamsColors[teamID].name;

  metadata.title = teamName + " | Big Football";
  
  const items = {
    "overview": { content: <Overview teamID={ teamID } /> }, 
    "schedule": { content: <ScheduleHome teamID={ teamID } /> }, 
    "roster": { content: <RosterHome teamID={ teamID } /> }, 
    "statistics": { content: <StatisticsHome teamID={ teamID } /> }
  };
  
  return (
    <>
      <TeamProvider teamID={ teamID }>
          { children }
          <Tabs items={ items } />  
      </TeamProvider> 
    </>
  );
}
