import type { Metadata } from "next";
import TeamProvider from "@/app/contextProviders/teamProvider";

import Overview from "@/app/teams/[teamID]/@tabs/overview/page";
import Schedule from "@/app/teams/[teamID]/@tabs/schedule/page";
import Roster from "@/app/teams/[teamID]/@tabs/roster/page";
import Statistics from "@/app/teams/[teamID]/@tabs/statistics/page";
import Tabs from "@/app/components/Tabs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, ...props }) {
  const items = {
    "overview": { content: <Overview /> }, 
    "schedule": { content: <Schedule /> }, 
    "roster": { content: <Roster /> }, 
    "statistics": { content: <Statistics /> }
  };

  return (
    <>
        <TeamProvider teamID={ props.params.teamID }>
          { children }
          <Tabs items={ items } />  
        </TeamProvider>
    </>
  );
}
